### ISSUE TITLE
Mobile: Title menu should flow below title

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#10456]
Flexbox!

**Comment by hypeJunction** [comment]
This is what I have in one of my themes:

```css

.elgg-layout-header {
  border-bottom: 1px solid #f1f1f1;
}

.elgg-layout-header > .elgg-head {
  display: -webkit-flex;
  display: flex;
  -webkit-flex-wrap: nowrap;
  flex-wrap: nowrap;
  -webkit-align-items: center;
  align-items: center;
  line-height: 20px;
  padding: 15px;
}
@media (max-width: 820px) {
  .elgg-layout-header > .elgg-head {
    -webkit-flex-wrap: nowrap;
    flex-wrap: nowrap;
  }
}

.elgg-layout-header > .elgg-head > h2 {
  -webkit-order: 1;
  order: 1;
  -webkit-flex: 1 1 auto;
  flex: 1 1 auto;
}

.elgg-layout-header > .elgg-head > .elgg-menu {
  -webkit-flex: 1 1 auto;
  flex: 1 1 auto;
  -webkit-order: 2;
  order: 2;
  text-align: right;
}
```
