### ISSUE TITLE
master: missing lightbox styling on admin backend

### ISSUE THREAD

**Issue by jdalsem** [Elgg/Elgg#11002]
i think i see javascript errors

**Comment by mrclay** [comment]
The colorbox CSS references the relative link `graphics/ajax_loader_bw.gif`. We need to prepend a few `../` to make that work.

Only style issue I see is we purposefully single out modules to have no padding. Unsure why.

```css
#cboxLoadedContent > .elgg-module:only-child {
    padding: 0;
}
```
