### ISSUE TITLE
master admin: "Logged in as ..." looks like a link

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#11028]
Due to output/url change I assume.

**Comment by jdalsem** [comment]
yes... i does get the class `elgg-non-link`.. should we add styling to that class?
```css
cursor: default;
text-decoration: none;
```

**Comment by jdalsem** [comment]
or make it a link to profile?

**Comment by hypeJunction** [comment]
```css
a[href="javascript:void(0)"] {
   cursor: default;
}
```
