### ISSUE TITLE
elgg-3: table headers/cells break wrong

### ISSUE THREAD

**Issue by jeabakker** [Elgg/Elgg#11731]
They break mid-word instead of at a whitespace

![image](https://user-images.githubusercontent.com/881958/36301353-c9734568-1304-11e8-9e6a-04766a8ad76e.png)

```css
.elgg-table td, .elgg-table th, .elgg-table-alt td, .elgg-table-alt th {
    border-style: solid;
    border-width: 0 0 1px;
    border-color: #e6e6ea;
    padding: .5em .75em;
    vertical-align: top;
    background-color: white;
    word-break: break-all;
}
```

why: ` word-break: break-all;`

**Comment by jeabakker** [comment]
also 

```css
.elgg-table thead th, .elgg-table-alt thead th {
    font-weight: bold;
    text-align: left;
    border-width: 0 0 2px;
}
```

` text-align: left;` why?? default is `left` right?
