### ISSUE TITLE
Deprecation warning end up in CSS files as html

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7047]
My minification wasn't working, so I ended up finding this.

```css
.thewire-post .elgg-content {
	margin: 10px 5px;
}
<pre class="elgg-logger-data">WARNING: Deprecated in 1.8: Do not rely on $vars[&quot;url&quot;] being available in views: output/icon Called from [#9] D:\wamp\www\hypejunction19\engine\classes\Elgg\DeprecationWrapper.php:117&lt;br /&gt; -&gt; [#8] D:\wamp\www\hypejunction19\engine\classes\Elgg\DeprecationWrapper.php:99&lt;br /&gt; -&gt; [#7] D:\wamp\www\hypejunction19\mod\event_manager\views\default\event_manager\css\site.php:2</pre>
/* Event global */
.event_manager_required {
	color: #AAAAAA;
}
```
