### ISSUE TITLE
Helper margin and padding classes

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#7907]
I often get frustrated with the use of CSS helper classes for margins and paddings, a-la `mrm` and `pal`.

They are quite difficult to work with in custom themes. The moment you change the alignment of inline items right and left margins, for example, shift the stuff in the wrong direction.

One common place where these classes are used is buttons, Let's create a buttonbank view, that will use `elgg-menu elgg-menu-hz`. Will take `$vars['buttons'] = [$button1, $button2]`

We should also text-alignment classes to core, e.g. `text-right` and `text-left`, and use them for determining left/right margins and paddings, in cases where an element is padded from one side only. This will also be helpful for RTL themes.

``` css
.elgg-buttonbank > li {
 margin-right: 10px;
}
.elgg-buttonbank.text-right > li {
  margin-right: 0;
  margin-left: 10px;
}
```
