### ISSUE TITLE
Inject some commonly-needed paths into CSS rendered through views

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#7915]
Currently if we want to use .css views, or SCSS as a preprocessor, we can't get runtime paths like elgg_get_site_url(). We could select a few of these and have Elgg inject them on serving. E.g.

```css
body {
    background-image: url(__ROOT_PATH/mod/foo/cats.gif?__SIMPLECACHE_VERSION);
}
```

Thoughts @PerJensen @hypeJunction ?
