### ISSUE TITLE
Refinement of elgg-list-river margin

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#8124]
The thing is that the new layout of elgg-river-responses has led to an unwanted margin, as seen here:
![elgg-river-responses](https://cloud.githubusercontent.com/assets/1220345/7061806/959afdb2-de96-11e4-99c6-2634c323c258.jpg)
So we have to remove:
```CSS
.elgg-river-responses {
	margin-top: 15px;
}
```
The declaration, however, was added (wrongly) to adjust the elgg-river-responses margin-top in widgets because of a few other declarations:
```CSS
.elgg-list-river {
	margin-top: -10px;
}
.elgg-module .elgg-list {
	margin-top: 0;
}
```
I suggest that we remove all and adjusts for margin-top in widgets like this:
```CSS
/* Group modules */
.elgg-module > .elgg-body > .elgg-list,
/* Profile and dashboard widgets */
.elgg-module .elgg-widget-content > .elgg-list {
	margin-top: 0;
}
```
Hope the explanation makes sense, try adding the changes.
