### ISSUE TITLE
Allow loading static views from .css and css/ views without elgg_get_simplecache_url

### ISSUE THREAD

**Issue by ewinslow** [Elgg/Elgg#8486]
Great suggestion from @hypeJunction.

I've always thought the solution would ultimately be to use relative urls and then do some sort of pre-processing with the "view,all" hook to replace it with the full path. We could do this at view render time based on the name of the current view so that even if a view is appended to another (as many/most css views are), you still get intuitive rendering behavior.

Suppose you have these three views:

```php
// css/elgg.php
echo elgg_view('css/elgg/button');
```

```css
/* css/elgg/button.php */
.elgg-button {
  background-image: url(./button-background.jpg)
}
```

```
// css/elgg/button-background.png
... some image file ...
```

You don't want `css/elgg.php` to end up looking like this:
```css
/* Loaded from .../default/css/elgg */
.elgg-button {
  background-image: url(./button-background.jpg)
}
```

Because then the loaded URL would be `.../default/css/button-background.jpg`
instead of the intended `.../default/css/elgg/button-background.jpg`

Hoping that checking for relative URLs doesn't prove to be too difficult, otherwise this seems like a great feature that would allow us to get rid of the need for PHP CSS 99% of the time...

**Comment by hypeJunction** [comment]
We could use a mixin approach to avoid complex regex rules.

```css
.elgg-button {
   background-image: elgg-view('css/elgg/button');
}
```

This would keep it inline with PHP and make it easier to substitute ```elgg-view($view)``` with a ```url($simplecache_url)```
