### ISSUE TITLE
errors in accessing graphics

### ISSUE THREAD

**Issue by PerJensen** [Elgg/Elgg#8720]
Assuming that the graphics must be available to CSS files when mapped with a views.php ( #8553 ).

However, this block returns an error:
```CSS
.elgg-ajax-loader {
	background: white url('october/loader.gif') no-repeat center center;
	min-height: 31px;
	min-width: 31px;
}
```
"NetworkError: 403 Forbidden - http://localhost/sites/elgg-2.0/cache/0/default/october/loader.gif"
