### ISSUE TITLE
2.0: message userpicker leaves ARIA thing visible

### ISSUE THREAD

**Issue by mrclay** [Elgg/Elgg#8782]
```html
<span role="status" aria-live="assertive" aria-relevant="additions" class="ui-helper-hidden-accessible"><div style="display: none;"></div><div>admin</div></span>
```

**Comment by mrclay** [comment]
UI demo has this:
```css
.ui-helper-hidden-accessible {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```
