### ISSUE TITLE
Simplecache resource URL

### ISSUE THREAD

**Issue by hypeJunction** [Elgg/Elgg#8817]
Am I correct in concluding that simplecache URLs can not be resolved without PHP? I am compiling CSS with SASS for Elgg 2.0 and it seems that simplecache URLs are all timestamped, so for now I am going back to using the graphics folder.

**Comment by ewinslow** [comment]
Can you give some more details of the problem you're having?

**Comment by hypeJunction** [comment]
I want to use /mod/my_plugin/views/default/images/some_image.jpg in my CSS without PHP.

**Comment by ewinslow** [comment]
How do you expect to do this? What have you tried? What does your css file look like? Did you try a relative url from the css file? Is the css file also in views?

**Comment by hypeJunction** [comment]
My bad. I wasn't paying attention to the simplecache URL of the CSS file. It was extending the core css view.

This works
```css
// my.css in /views/default/my.css extending elgg.css.php
// image.jpg in /views/default/images/image.jpg
.my-div {
   background-image: url(images/image.jpg);
}
```
